### ISSUE TITLE
[feature] Support for Terraform 0.13

### ISSUE THREAD

**Issue by arnaudlh** [Azure/caf-terraform-landingzones#45]
# Proposal

Add support for Terraform 0.13 in two waves:

1. **Compatible**: able to run on Terraform 13. possibly on Terraform 12.
2. **Optimized**: leverage Terraform 13: for landing zones leverage features as ```count``` ```for_each``` ```depends_on```.

## Landing zones
- [x] landingzone_vdc_demo
- [x] landingzone_hub_spoke
- [x] landingzone_caf_foundations
- [x] landingzone_secure_vnet_dmz
- [x] landingzone_hub_mesh 

## Dependencies
- [X]  [Provider azurecaf present in the registry](https://registry.terraform.io/providers/aztfmod/azurecaf/latest)

**Comment by frodopackets** [comment]
When trying to instantiate landingzone_caf_foundations on 0.13beta2 via TFE or the local binary, I'm observing issues where its trying to find the azurecaf provider within aztfmod (this is signed and successful) as well as the hashicorp namespace (this is not for obvious reasons).  Since it fails to find azurecaf in the hashicorp namespace the plan fails.   This doesn't happen unless I start taking advantage of the blueprint/modules - just setting the required provider and using an azurecaf resource works fine.  I can't seem to locate where the problem might be.  At first I assumed we just had an azurecaf provider called out in a module/submodule without the aztfmod namespace being defined but I can't find it.   I even removed version pinning to see if I was leveraged an out of date module.    Obviously 0.13 is beta, and this is still work in progress - but it seemed worth calling out the issue here since it seemed to be working for TFC in the demo on youtube.

**Comment by arnaudlh** [comment]
Hi @frodopackets, we use the provider from the registry, available [here](https://registry.terraform.io/providers/aztfmod/azurecaf/latest)
and you should call it using: 
```hcl
terraform {
  required_providers {
    azurecaf = {
      source = "aztfmod/azurecaf"
    }
  }
}
```
The ```hashicorp/azurecaf``` error message you are referring to - is due to modules trying to locate the provider "the old way". 

Those modules are in test now and you can check a working version, just for the purpose of quick demo here: https://github.com/arnaudlh/caf-terraform-landingzones-tfc/tree/master/landingzones/landingzone_caf_foundations 

HTH.

**Comment by arnaudlh** [comment]
Working branch for this one is vnext13 - https://github.com/Azure/caf-terraform-landingzones/tree/vnext13

**Comment by arnaudlh** [comment]
since GA of Terraform 0.13 has been pushed to 10th August as per https://github.com/hashicorp/terraform/issues/25016
we will align and release 13 capabilities in 2008 (august release). in the meantime you can still use the ```vnext13``` branch (https://github.com/Azure/caf-terraform-landingzones/tree/vnext13) to follow the updates
