### ISSUE TITLE
Dev Container fail, not able to run rover on WSL2 [bug]

### ISSUE THREAD

**Issue by rofangaci** [Azure/caf-terraform-landingzones#74]
When i start the Dev Container on my VS code connect to WSL2, i got failure as following:
docker: Error response from daemon: \\wsl\Ubuntu-18.04\home\rofa\myWork%!(EXTRA
string=is not a valid Windows path).

I am not able to start Dev Container. two questions:
1. How do I use Rover without Dev Container?
2. Can I run tf directly without using Rover?

Thanks!

**Comment by bernardmaltais** [comment]
@rofangaci Hi, I am not part of the LZ team but I have been using / modding the solution for the past few months. What I can tell you is that something specific to your setup must be causing this error. I have not seen it personally. Perhaps try uninstalling docker and install a fresh stable copy of it.

2nd, no, you can't really run rover without a devcontainer. Technically you could run the container in WSL2 and mount the same volume as what devcontainer mount and you would be up and running... but it would be tedious.

3rd, can you run the landingzone directly without rover? I don't think you can the ones in this repo. I personally can run some of the landingzone I built without rover as long as they don't refer to other landingzone statefiles... but yes, technically you should be able to run most of the landingzone code outside of rover with minimal adjustments.

**Comment by arnaudlh** [comment]
hi @rofangaci  need to investigate your WSL+Docker configuration, put it into different directory for instance and see the behavior as our environment to run landing zones is the rover. 
If really not working on your laptop you can also use a 4th option which is to use visual studio codespaces [![VScodespaces](https://img.shields.io/endpoint?url=https%3A%2F%2Faka.ms%2Fvso-badge)](https://online.visualstudio.com/environments/new?name=caf%20landing%20zones&repo=azure/caf-terraform-landingzones)

**Comment by Justin-DynamicD** [comment]
comment and a question, as I think its related to this topic.

Comment: make sure you are upgraded to support WSL2.  I dont believe rover will work properly on WSL1.

Question: @bernardmaltais as someone whos used this model for a few months now, I'm personally struggling on a couple concepts here that feel poorly documented.  Once you get your launchpad in place, can you keep landingzones in different repos?  It seems to me that I run into problems running rover in an repo that isnt precisely named "caf-terraform-landingzones", like the rover is expecting a very specific strucutre and simply portable in the way I assuemd it would be.  Ony way I can get it to work right now is to basically use a massive mono-repo for all my projects, which scales horrifically.

**Comment by bernardmaltais** [comment]
@Justin-DynamicD The name of the repo does not need to match "caf-terraform-landingzones". For example, here is a template that I use to deploy landingzones in my Government Department I work for: https://github.com/ssc-spc-cloud-nuage/eslz-template

As you can se the repo name is totally different. There is a few things that need to line up under the hood. If you look at the github repo I just shared you will notice I created wrapper scripts that I use extensively to actually deploy landing zones. I also make extensive use of .devcontainer to make sure I have my deployment build exactly as I need. It is a slightly customized version of what is provided in the caf-terraform-landingzones repo. For the most part I have modified the rover.sh script as to not auto apply by default but instead ask for confirmation. This is much safer as I have lost many infra to a bad apply that should not have been approved if I had a chance to catch what it was about to do ;-)

Once you get the hang of this it really really work well. You might want to try to deploy my eslz-template in a test subscription to see it in action and see if it would do what you need. Obviously you can totally change it and use it as a foundation for what you need also. Feel free to borrow, rip and replace ;-)

**Comment by Justin-DynamicD** [comment]
Thank you for your insight on how you operate.  I ended up opening a bug on the rover build becuase, for whatever reason, the container crashes/fails to run for me, as in it litterally refuses to launch even if I just clone and open up the rover repo.  Just DOA.

I have a good dozen custom local containers I use for remote development across differetn clients, all operate fine, but the rover is basically finicky to the point of being essentially useless for me.

And yeah, all my docker continers are ubuntu as well.

Honestly I wish they just wrapped that statefile logic into an executable like terragrunt does.  It would have been a cleaner wrapper that would have made the rover a lot more portable ... but now Im still trying to figure out how on earth to not get it to implode when I try to use it.  That and the various landingzone tempaltes all assum the rocer logic is in play, asking for GUIDs and other goodies if i try to operate without it.  Just feels like a house of cards to me.

**Comment by bernardmaltais** [comment]
@Justin-DynamicD It is not so bad. I think if you use the blueprint as provided by the caf-terraform-landingzones it will be very much tightly intertwined... This is why I wrote my own that are much more decoupled. My L1 blueprint only depend on minimal resources from L0: https://github.com/ssc-spc-cloud-nuage/eslz-template/blob/master/L1_blueprint_base/code/0-L0_remote_state.tf

My L2 blueprint does depend on a few resources deployed in L1 but I keep it at a manageable level: https://github.com/ssc-spc-cloud-nuage/eslz-template/blob/master/L2_blueprint_project/code/0-L1-remote-state.tf

The ability to easily leverage resources from other levels is a blessing and can be a curse... but it is not as bad as being a deck of cards. At least based on my 6 months experience. My biggest gripe with the whole thing is that sometime, if I want to manipulate the statefile manually using terraform it will fail because it can't find some of the remote resources ;-( I have not found a way around it yet but I have not looked very hard either ;-) Might just be that I will have to call my terraform.sh script like rover.sh is... with env vars filled with the needed values.

If you write your own blueprint like I did in my case you can also opt to never use the other l1vels resources and simply do it using data resources calls. In the end I found the data calls were more of a pain vs the simplicity of using remote resources states and living with the inconveniance of not being to do everything I used to via terraform exe calls.

Now... I don't know what is going up with your issue running the devcontainer locally. I suspect some local docker/os issue. I have been running it just fine on WSL2, Linux and codespaces. I now totally switched to using codespaces as it is so much nicer to be able to rely on a remote deployment machine. I no longer have to build my dev env on every machine I might use. I just need VSCode and access to my codespaces ;-)

**Comment by Justin-DynamicD** [comment]
For whatever reason I could not get devcontainer to run locally.  So I litterally just did a fresh docker-compose build and that container worked?  I dont know what the difference is, but I basically set up an AzureDevOps pipeline to build a company rover and that container works while the public one fails.  If anyone could explain that logic to me that would be interesting, but at this point I think maintaining a local rover is proibably healthier anyway, as I would like packer and soem other tools in there.

That at least untangled my initial mess and answers that yes, I CAN make my own repo structure without worry of implosion. As for decoupling, I 100% agree there as well.  Justlooks like a bit more work to setup than anticipated.

**Comment by LaurentLesle** [comment]
Closing now
